### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by chevanlol360** [arj1231/kernel_lge_msm8226-old#1]
Hey i have a few questions about this kernel and its history, do you mind if i ask here?

**Comment by arj1231** [comment]
Sure its based on. Quarx2k msm8226

**Comment by chevanlol360** [comment]
Yeah i figured it would be based on his kernel. Did you implement the volt files into the kernel or did he  do it? and since the kernel was really made for another chip, did it take a lot of work to configure it to fit the needs of the volt?

**Comment by arj1231** [comment]
I had to incorporate some volt refernces, it wasn't too difficult seeing as the l90/g2 mini/ & volt are pretty similar, they use the same chipset just different touchscreens really.

**Comment by chevanlol360** [comment]
im looking into the LG Leon, any chance that with a little bit of work, this kernel would boot with it? Trying to get a cm12 kernel going, the leon comes with 5.0.1 initially but do you think i should use this kernel and implement as much as i can to see if it will boot or should i go off the stock kernel and build cm and fix any errors that come along?

leon chipset Chipset    

Qualcomm MSM8916 Snapdragon 410
CPU Quad-core 1.2 GHz Cortex-A53

**Comment by arj1231** [comment]
I would start with trying a similar kernel tree from a device with same chipset.

pdadb.net/index.php?m=pdamaster&posted=1&cpu=a8916

https://github.com/TeamRegular/android_kernel_lge_g4stylus

You could try the kernel on my github, but im pretty sure it would need some heavy modifications to make it work on that device.

**Comment by chevanlol360** [comment]
yeah quarx just replied and said its best if i use the stock kernel source for the device. alright thanks for the help:)
